### ISSUE TITLE
Fix statute navigation in search results

### ISSUE THREAD

**Issue by DanPaguirigan** [OpenHRS/openhrs-mobile-app#6]
### Description
The navigation arrows on statutes opened from a search result, are no longer functional. 
Feature broke after infinite scroll was added to search results (line 32 in search/search.ts).
### Expected Behavior 
Arrows navigate the user through the statutes in the search result.

https://github.com/OpenHRS/openhrs-mobile-app/blob/d52d2a8d7faab47b2839c221e17979c1548f6ceb/src/pages/statue/statue.ts#L105-L131

**Comment by chrisoh1** [comment]
fixed
